# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: goldenowl_development
  pool:     5
  username: root
  password: root
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: goldenowl_test
  pool:     5
  username: root
  password: root
  template: template0

staging:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: goldenowl_staging
  pool:     5
  username: root
  password: root
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: goldenowl_production
  pool:     5
  username: root
  password: root
  template: template0
